const demonDays = {
  name: "Demon Days",
  artist: "Gorillaz",
  year: 2005,
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Intro",
      artists: ["Gorillaz"],
      streams: 18908432,
      duration: "1:07",
      isLiked: false,
    },
    {
      songId: 2,
      title: "Last Living Souls",
      artists: ["Gorillaz"],
      streams: 46865703,
      duration: "3:15",
      isLiked: true,
    },
    {
      songId: 3,
      title: "Kids with Guns",
      artists: ["Gorillaz", "Neneh Cherry"],
      streams: 174780895,
      duration: "3:45",
      isLiked: true,
    },
    {
      songId: 4,
      title: "O Green World",
      artists: ["Gorillaz"],
      streams: 93496076,
      duration: "4:35",
      isLiked: false,
    },
    {
      songId: 5,
      title: "Dirty Harry (feat. Bootie Brown)",
      artists: ["Gorillaz", "Bootie Brown"],
      streams: 309247622,
      duration: "3:50",
      isLiked: true,
    },
    {
      songId: 6,
      title: "Feel Good Inc.",
      artists: ["Gorillaz", "De La Soul"],
      streams: 1802291245,
      duration: "3:42",
      isLiked: true,
    },
    {
      songId: 7,
      title: "El Mañana",
      artists: ["Gorillaz"],
      streams: 124825180,
      duration: "3:55",
      isLiked: false,
    },
    {
      songId: 8,
      title: "Every Planet We Reach Is Dead",
      artists: ["Gorillaz"],
      streams: 50652950,
      duration: "4:55",
      isLiked: false,
    },
    {
      songId: 9,
      title: "Nobember Has Come",
      artists: ["Gorillaz", "MF DOOM"],
      streams: 84325352,
      duration: "2:45",
      isLiked: true,
    },
    {
      songId: 10,
      title: "All Alone",
      artists: ["Gorillaz", "Martina Topley-Bird", "Roots Manuva"],
      streams: 53267312,
      duration: "3:33",
      isLiked: false,
    },
    {
      songId: 11,
      title: "White Light",
      artists: ["Gorillaz"],
      streams: 27603042,
      duration: "2:13",
      isLiked: false,
    },
    {
      songId: 12,
      title: "DARE (feat. Shaun Ryder & Roses Gabor)",
      artists: ["Gorillaz", "Shaun Ryder", "Roses Gabor"],
      streams: 569024364,
      duration: "4:04",
      isLiked: true,
    },
    {
      songId: 13,
      title: "Fire Coming out of the Moneky's Head",
      artists: ["Gorillaz"],
      streams: 41189793,
      duration: "3:19",
      isLiked: false,
    },
    {
      songId: 14,
      title: "Don't Get Lost in Heaven",
      artists: ["Gorillaz"],
      streams: 28286122,
      duration: "2:11",
      isLiked: false,
    },
    {
      songId: 15,
      title: "Demon Days",
      artists: ["Gorillaz"],
      streams: 32635089,
      duration: "4:28",
      isLiked: false,
    },
  ],
};

export { demonDays };
