const demonDays = {
  id: "001",
  name: "Demon Days",
  artist: "Gorillaz",
  year: 2005,
  duration: 3102,
  image: "/playerControls/Gorillaz_Demon_Days.png",
  colorFrom: "#a04848",
  colorTo: "#640e17",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Intro",
      artists: ["Gorillaz"],
      streams: 18908432,
      duration: 67,
      isLiked: false,
    },
    {
      songId: 2,
      title: "Last Living Souls",
      artists: ["Gorillaz"],
      streams: 46865703,
      duration: 295,
      isLiked: true,
    },
    {
      songId: 3,
      title: "Kids with Guns",
      artists: ["Gorillaz", "Neneh Cherry"],
      streams: 174780895,
      duration: 225,
      isLiked: true,
    },
    {
      songId: 4,
      title: "O Green World",
      artists: ["Gorillaz"],
      streams: 93496076,
      duration: 275,
      isLiked: false,
    },
    {
      songId: 5,
      title: "Dirty Harry (feat. Bootie Brown)",
      artists: ["Gorillaz", "Bootie Brown"],
      streams: 309247622,
      duration: 230,
      isLiked: true,
    },
    {
      songId: 6,
      title: "Feel Good Inc.",
      artists: ["Gorillaz", "De La Soul"],
      streams: 1802291245,
      duration: 225,
      isLiked: true,
    },
    {
      songId: 7,
      title: "El Mañana",
      artists: ["Gorillaz"],
      streams: 124825180,
      duration: 235,
      isLiked: false,
    },
    {
      songId: 8,
      title: "Every Planet We Reach Is Dead",
      artists: ["Gorillaz"],
      streams: 50652950,
      duration: 295,
      isLiked: false,
    },
    {
      songId: 9,
      title: "Nobember Has Come",
      artists: ["Gorillaz", "MF DOOM"],
      streams: 84325352,
      duration: 165,
      isLiked: true,
    },
    {
      songId: 10,
      title: "All Alone",
      artists: ["Gorillaz", "Martina Topley-Bird", "Roots Manuva"],
      streams: 53267312,
      duration: 213,
      isLiked: false,
    },
    {
      songId: 11,
      title: "White Light",
      artists: ["Gorillaz"],
      streams: 27603042,
      duration: 133,
      isLiked: false,
    },
    {
      songId: 12,
      title: "DARE (feat. Shaun Ryder & Roses Gabor)",
      artists: ["Gorillaz", "Shaun Ryder", "Roses Gabor"],
      streams: 569024364,
      duration: 244,
      isLiked: true,
    },
    {
      songId: 13,
      title: "Fire Coming out of the Moneky's Head",
      artists: ["Gorillaz"],
      streams: 41189793,
      duration: 199,
      isLiked: false,
    },
    {
      songId: 14,
      title: "Don't Get Lost in Heaven",
      artists: ["Gorillaz"],
      streams: 28286122,
      duration: 131,
      isLiked: false,
    },
    {
      songId: 15,
      title: "Demon Days",
      artists: ["Gorillaz"],
      streams: 32635089,
      duration: 268,
      isLiked: false,
    },
  ],
};

const inRainbows = {
  id: "002",
  name: "In Rainbows",
  artist: "Radiohead",
  year: 2007,
  duration: 2532, // 42 minutos y 12 segundos
  image: "/playerControls/Inrainbowscover.png",
  colorFrom: "#500810",
  colorTo: "#500810",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "15 Step",
      artists: ["Radiohead"],
      streams: 180000000,
      duration: 236,
      isLiked: true,
    },
    {
      songId: 2,
      title: "Bodysnatchers",
      artists: ["Radiohead"],
      streams: 120000000,
      duration: 240,
      isLiked: false,
    },
    {
      songId: 3,
      title: "Nude",
      artists: ["Radiohead"],
      streams: 170000000,
      duration: 263,
      isLiked: true,
    },
    {
      songId: 4,
      title: "Weird Fishes/Arpeggi",
      artists: ["Radiohead"],
      streams: 150000000,
      duration: 305,
      isLiked: true,
    },
    {
      songId: 5,
      title: "All I Need",
      artists: ["Radiohead"],
      streams: 160000000,
      duration: 222,
      isLiked: true,
    },
    {
      songId: 6,
      title: "Faust Arp",
      artists: ["Radiohead"],
      streams: 80000000,
      duration: 129,
      isLiked: false,
    },
    {
      songId: 7,
      title: "Reckoner",
      artists: ["Radiohead"],
      streams: 140000000,
      duration: 273,
      isLiked: true,
    },
    {
      songId: 8,
      title: "House of Cards",
      artists: ["Radiohead"],
      streams: 110000000,
      duration: 336,
      isLiked: false,
    },
    {
      songId: 9,
      title: "Jigsaw Falling Into Place",
      artists: ["Radiohead"],
      streams: 95000000,
      duration: 295,
      isLiked: true,
    },
    {
      songId: 10,
      title: "Videotape",
      artists: ["Radiohead"],
      streams: 130000000,
      duration: 233,
      isLiked: true,
    },
  ],
};

const thriller = {
  id: "003",
  name: "Thriller",
  artist: "Michael Jackson",
  year: 1982,
  duration: 2580, // 43 minutos exactos
  image: "/playerControls/Michael_Jackson_-_Thriller.png",
  colorFrom: "#778f8f",
  colorTo: "#243a3a",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Wanna Be Startin' Somethin'",
      artists: ["Michael Jackson"],
      streams: 234567891,
      duration: 362,
      isLiked: true,
    },
    {
      songId: 2,
      title: "Baby Be Mine",
      artists: ["Michael Jackson"],
      streams: 67543219,
      duration: 260,
      isLiked: false,
    },
    {
      songId: 3,
      title: "The Girl Is Mine",
      artists: ["Michael Jackson", "Paul McCartney"],
      streams: 98234567,
      duration: 223,
      isLiked: false,
    },
    {
      songId: 4,
      title: "Thriller",
      artists: ["Michael Jackson"],
      streams: 549876321,
      duration: 358,
      isLiked: true,
    },
    {
      songId: 5,
      title: "Beat It",
      artists: ["Michael Jackson"],
      streams: 478901234,
      duration: 258,
      isLiked: true,
    },
    {
      songId: 6,
      title: "Billie Jean",
      artists: ["Michael Jackson"],
      streams: 834567890,
      duration: 294,
      isLiked: true,
    },
    {
      songId: 7,
      title: "Human Nature",
      artists: ["Michael Jackson"],
      streams: 123456789,
      duration: 248,
      isLiked: true,
    },
    {
      songId: 8,
      title: "P.Y.T. (Pretty Young Thing)",
      artists: ["Michael Jackson"],
      streams: 102345678,
      duration: 239,
      isLiked: false,
    },
    {
      songId: 9,
      title: "The Lady in My Life",
      artists: ["Michael Jackson"],
      streams: 74321098,
      duration: 299,
      isLiked: true,
    },
  ],
};

const theMiseducationOfLaurynHill = {
  id: "004",
  name: "The Miseducation of Lauryn Hill",
  artist: "Ms. Lauryn Hill",
  year: 1998,
  duration: 4765, // 1 hora, 19 minutos y 25 segundos
  image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
  colorFrom: "#7f2f2f",
  colorTo: "#621318",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Intro",
      artists: ["Ms. Lauryn Hill"],
      streams: 4531298,
      duration: 66,
      isLiked: false,
    },
    {
      songId: 2,
      title: "Lost Ones",
      artists: ["Ms. Lauryn Hill"],
      streams: 189034512,
      duration: 309,
      isLiked: true,
    },
    {
      songId: 3,
      title: "Ex-Factor",
      artists: ["Ms. Lauryn Hill"],
      streams: 274891345,
      duration: 337,
      isLiked: true,
    },
    {
      songId: 4,
      title: "To Zion",
      artists: ["Ms. Lauryn Hill", "Carlos Santana"],
      streams: 132458921,
      duration: 366,
      isLiked: true,
    },
    {
      songId: 5,
      title: "Doo Wop (That Thing)",
      artists: ["Ms. Lauryn Hill"],
      streams: 415672389,
      duration: 305,
      isLiked: true,
    },
    {
      songId: 6,
      title: "Superstar",
      artists: ["Ms. Lauryn Hill"],
      streams: 98451239,
      duration: 256,
      isLiked: false,
    },
    {
      songId: 7,
      title: "Final Hour",
      artists: ["Ms. Lauryn Hill"],
      streams: 67891234,
      duration: 269,
      isLiked: false,
    },
    {
      songId: 8,
      title: "When It Hurts So Bad",
      artists: ["Ms. Lauryn Hill"],
      streams: 104589321,
      duration: 293,
      isLiked: true,
    },
    {
      songId: 9,
      title: "I Used to Love Him",
      artists: ["Ms. Lauryn Hill", "Mary J. Blige"],
      streams: 89345122,
      duration: 323,
      isLiked: true,
    },
    {
      songId: 10,
      title: "Forgive Them Father",
      artists: ["Ms. Lauryn Hill"],
      streams: 67483920,
      duration: 328,
      isLiked: false,
    },
    {
      songId: 11,
      title: "Every Ghetto, Every City",
      artists: ["Ms. Lauryn Hill"],
      streams: 58934712,
      duration: 296,
      isLiked: false,
    },
    {
      songId: 12,
      title: "Nothing Even Matters",
      artists: ["Ms. Lauryn Hill", "D'Angelo"],
      streams: 132984568,
      duration: 361,
      isLiked: true,
    },
    {
      songId: 13,
      title: "Everything Is Everything",
      artists: ["Ms. Lauryn Hill"],
      streams: 198745632,
      duration: 237,
      isLiked: true,
    },
    {
      songId: 14,
      title: "The Miseducation of Lauryn Hill",
      artists: ["Ms. Lauryn Hill"],
      streams: 125678934,
      duration: 265,
      isLiked: true,
    },
    {
      songId: 15,
      title: "Can't Take My Eyes Off of You",
      artists: ["Ms. Lauryn Hill"],
      streams: 305981234,
      duration: 226,
      isLiked: true,
    },
    {
      songId: 16,
      title: "Tell Him",
      artists: ["Ms. Lauryn Hill"],
      streams: 87213455,
      duration: 259,
      isLiked: false,
    },
  ],
};

const nevermind = {
  id: "005",
  name: "Nevermind",
  artist: "Nirvana",
  year: 1991,
  duration: 2940, // 49 minutos
  image: "/playerControls/NirvanaNevermindalbumcover.jpg",
  colorFrom: "#0060a8",
  colorTo: "#003074",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Smells Like Teen Spirit",
      artists: ["Nirvana"],
      streams: 1356789345,
      duration: 301,
      isLiked: true,
    },
    {
      songId: 2,
      title: "In Bloom",
      artists: ["Nirvana"],
      streams: 432198765,
      duration: 254,
      isLiked: true,
    },
    {
      songId: 3,
      title: "Come as You Are",
      artists: ["Nirvana"],
      streams: 891234567,
      duration: 219,
      isLiked: true,
    },
    {
      songId: 4,
      title: "Breed",
      artists: ["Nirvana"],
      streams: 289345123,
      duration: 183,
      isLiked: false,
    },
    {
      songId: 5,
      title: "Lithium",
      artists: ["Nirvana"],
      streams: 576123890,
      duration: 257,
      isLiked: true,
    },
    {
      songId: 6,
      title: "Polly",
      artists: ["Nirvana"],
      streams: 234567890,
      duration: 179,
      isLiked: false,
    },
    {
      songId: 7,
      title: "Territorial Pissings",
      artists: ["Nirvana"],
      streams: 156789012,
      duration: 142,
      isLiked: false,
    },
    {
      songId: 8,
      title: "Drain You",
      artists: ["Nirvana"],
      streams: 298765432,
      duration: 223,
      isLiked: true,
    },
    {
      songId: 9,
      title: "Lounge Act",
      artists: ["Nirvana"],
      streams: 145678901,
      duration: 156,
      isLiked: false,
    },
    {
      songId: 10,
      title: "Stay Away",
      artists: ["Nirvana"],
      streams: 134567890,
      duration: 212,
      isLiked: false,
    },
    {
      songId: 11,
      title: "On a Plain",
      artists: ["Nirvana"],
      streams: 198765432,
      duration: 196,
      isLiked: false,
    },
    {
      songId: 12,
      title: "Something in the Way",
      artists: ["Nirvana"],
      streams: 654321987,
      duration: 231,
      isLiked: true,
    },
  ],
};

const toPimpAButterfly = {
  id: "006",
  name: "To Pimp a Butterfly",
  artist: "Kendrick Lamar",
  year: 2015,
  duration: 4787, // 1 hora, 19 minutos y 47 segundos
  image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
  colorFrom: "#535353",
  colorTo: "#363636",
  isLiked: true,
  songList: [
    {
      songId: 1,
      title: "Wesley's Theory",
      artists: ["Kendrick Lamar", "George Clinton", "Thundercat"],
      streams: 124567893,
      duration: 292,
      isLiked: false,
    },
    {
      songId: 2,
      title: "For Free? (Interlude)",
      artists: ["Kendrick Lamar"],
      streams: 78543210,
      duration: 122,
      isLiked: false,
    },
    {
      songId: 3,
      title: "King Kunta",
      artists: ["Kendrick Lamar"],
      streams: 345678912,
      duration: 220,
      isLiked: true,
    },
    {
      songId: 4,
      title: "Institutionalized",
      artists: ["Kendrick Lamar", "Bilal", "Anna Wise", "Snoop Dogg"],
      streams: 93456789,
      duration: 284,
      isLiked: false,
    },
    {
      songId: 5,
      title: "These Walls",
      artists: ["Kendrick Lamar", "Bilal", "Anna Wise", "Thundercat"],
      streams: 112345678,
      duration: 320,
      isLiked: true,
    },
    {
      songId: 6,
      title: "u",
      artists: ["Kendrick Lamar"],
      streams: 95432108,
      duration: 273,
      isLiked: true,
    },
    {
      songId: 7,
      title: "Alright",
      artists: ["Kendrick Lamar"],
      streams: 456789321,
      duration: 219,
      isLiked: true,
    },
    {
      songId: 8,
      title: "For Sale? (Interlude)",
      artists: ["Kendrick Lamar"],
      streams: 62345678,
      duration: 282,
      isLiked: false,
    },
    {
      songId: 9,
      title: "Momma",
      artists: ["Kendrick Lamar"],
      streams: 83456789,
      duration: 277,
      isLiked: false,
    },
    {
      songId: 10,
      title: "Hood Politics",
      artists: ["Kendrick Lamar"],
      streams: 78901234,
      duration: 294,
      isLiked: false,
    },
    {
      songId: 11,
      title: "How Much a Dollar Cost",
      artists: ["Kendrick Lamar", "James Fauntleroy", "Ronald Isley"],
      streams: 123456789,
      duration: 270,
      isLiked: true,
    },
    {
      songId: 12,
      title: "Complexion (A Zulu Love)",
      artists: ["Kendrick Lamar", "Rapsody"],
      streams: 92345678,
      duration: 260,
      isLiked: false,
    },
    {
      songId: 13,
      title: "The Blacker the Berry",
      artists: ["Kendrick Lamar"],
      streams: 198765432,
      duration: 308,
      isLiked: true,
    },
    {
      songId: 14,
      title: "You Ain’t Gotta Lie (Momma Said)",
      artists: ["Kendrick Lamar"],
      streams: 71234567,
      duration: 245,
      isLiked: false,
    },
    {
      songId: 15,
      title: "i",
      artists: ["Kendrick Lamar"],
      streams: 267890123,
      duration: 315,
      isLiked: true,
    },
    {
      songId: 16,
      title: "Mortal Man",
      artists: ["Kendrick Lamar"],
      streams: 85432109,
      duration: 732,
      isLiked: true,
    },
  ],
};

const likedAlbums = [
  demonDays,
  thriller,
  theMiseducationOfLaurynHill,
  inRainbows,
  toPimpAButterfly,
  nevermind,
];
export {
  likedAlbums,
  demonDays,
  thriller,
  theMiseducationOfLaurynHill,
  inRainbows,
  toPimpAButterfly,
  nevermind,
};
