export type TSong = {
  id: string;
  album: string;
  title: string;
  artists: string[];
  streams: number;
  duration: number;
  image: string;
  isLiked: boolean;
};

export type TAlbum = {
  id: string;
  name: string;
  artist: string;
  year: number;
  duration: number;
  image: string;
  colorFrom: string;
  colorTo: string;
  isLiked: boolean;
  songList: TSong[];
};

const demonDays: TAlbum = {
  id: "001",
  name: "Demon Days",
  artist: "Gorillaz",
  year: 2005,
  duration: 3102,
  image: "/playerControls/Gorillaz_Demon_Days.png",
  colorFrom: "#a04848",
  colorTo: "#640e17",
  isLiked: true,
  songList: [
    {
      id: "001-01",
      album: "001",
      title: "Intro",
      artists: ["Gorillaz"],
      streams: 18908432,
      duration: 67,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-02",
      album: "001",
      title: "Last Living Souls",
      artists: ["Gorillaz"],
      streams: 46865703,
      duration: 295,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-03",
      album: "001",
      title: "Kids with Guns",
      artists: ["Gorillaz", "Neneh Cherry"],
      streams: 174780895,
      duration: 225,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-04",
      album: "001",
      title: "O Green World",
      artists: ["Gorillaz"],
      streams: 93496076,
      duration: 275,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-05",
      album: "001",
      title: "Dirty Harry (feat. Bootie Brown)",
      artists: ["Gorillaz", "Bootie Brown"],
      streams: 309247622,
      duration: 230,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-06",
      album: "001",
      title: "Feel Good Inc.",
      artists: ["Gorillaz", "De La Soul"],
      streams: 1802291245,
      duration: 225,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-07",
      album: "001",
      title: "El Mañana",
      artists: ["Gorillaz"],
      streams: 124825180,
      duration: 235,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-08",
      album: "001",
      title: "Every Planet We Reach Is Dead",
      artists: ["Gorillaz"],
      streams: 50652950,
      duration: 295,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-09",
      album: "001",
      title: "Nobember Has Come",
      artists: ["Gorillaz", "MF DOOM"],
      streams: 84325352,
      duration: 165,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-10",
      album: "001",
      title: "All Alone",
      artists: ["Gorillaz", "Martina Topley-Bird", "Roots Manuva"],
      streams: 53267312,
      duration: 213,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-11",
      album: "001",
      title: "White Light",
      artists: ["Gorillaz"],
      streams: 27603042,
      duration: 133,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-12",
      album: "001",
      title: "DARE (feat. Shaun Ryder & Roses Gabor)",
      artists: ["Gorillaz", "Shaun Ryder", "Roses Gabor"],
      streams: 569024364,
      duration: 244,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: true,
    },
    {
      id: "001-13",
      album: "001",
      title: "Fire Coming out of the Moneky's Head",
      artists: ["Gorillaz"],
      streams: 41189793,
      duration: 199,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-14",
      album: "001",
      title: "Don't Get Lost in Heaven",
      artists: ["Gorillaz"],
      streams: 28286122,
      duration: 131,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
    {
      id: "001-15",
      album: "001",
      title: "Demon Days",
      artists: ["Gorillaz"],
      streams: 32635089,
      duration: 268,
      image: "/playerControls/Gorillaz_Demon_Days.png",
      isLiked: false,
    },
  ],
};

const inRainbows: TAlbum = {
  id: "002",
  name: "In Rainbows",
  artist: "Radiohead",
  year: 2007,
  duration: 2532, // 42 minutos y 12 segundos
  image: "/playerControls/Inrainbowscover.png",
  colorFrom: "#500810",
  colorTo: "#500810",
  isLiked: true,
  songList: [
    {
      id: "002-01",
      album: "002",
      title: "15 Step",
      artists: ["Radiohead"],
      streams: 180432119,
      duration: 236,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-02",
      album: "002",
      title: "Bodysnatchers",
      artists: ["Radiohead"],
      streams: 119847235,
      duration: 240,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: false,
    },
    {
      id: "002-03",
      album: "002",
      title: "Nude",
      artists: ["Radiohead"],
      streams: 170283442,
      duration: 263,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-04",
      album: "002",
      title: "Weird Fishes/Arpeggi",
      artists: ["Radiohead"],
      streams: 149938717,
      duration: 305,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-05",
      album: "002",
      title: "All I Need",
      artists: ["Radiohead"],
      streams: 159372811,
      duration: 222,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-06",
      album: "002",
      title: "Faust Arp",
      artists: ["Radiohead"],
      streams: 79833155,
      duration: 129,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: false,
    },
    {
      id: "002-07",
      album: "002",
      title: "Reckoner",
      artists: ["Radiohead"],
      streams: 140128492,
      duration: 273,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-08",
      album: "002",
      title: "House of Cards",
      artists: ["Radiohead"],
      streams: 110762304,
      duration: 336,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: false,
    },
    {
      id: "002-09",
      album: "002",
      title: "Jigsaw Falling Into Place",
      artists: ["Radiohead"],
      streams: 95432186,
      duration: 295,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
    {
      id: "002-10",
      album: "002",
      title: "Videotape",
      artists: ["Radiohead"],
      streams: 130597024,
      duration: 233,
      image: "/playerControls/Inrainbowscover.png",
      isLiked: true,
    },
  ],
};

const thriller: TAlbum = {
  id: "003",
  name: "Thriller",
  artist: "Michael Jackson",
  year: 1982,
  duration: 2580, // 43 minutos exactos
  image: "/playerControls/Michael_Jackson_-_Thriller.png",
  colorFrom: "#778f8f",
  colorTo: "#243a3a",
  isLiked: true,
  songList: [
    {
      id: "003-01",
      album: "003",
      title: "Wanna Be Startin' Somethin'",
      artists: ["Michael Jackson"],
      streams: 234982731,
      duration: 362,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
    {
      id: "003-02",
      album: "003",
      title: "Baby Be Mine",
      artists: ["Michael Jackson"],
      streams: 67514862,
      duration: 260,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: false,
    },
    {
      id: "003-03",
      album: "003",
      title: "The Girl Is Mine",
      artists: ["Michael Jackson", "Paul McCartney"],
      streams: 98273428,
      duration: 223,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: false,
    },
    {
      id: "003-04",
      album: "003",
      title: "Thriller",
      artists: ["Michael Jackson"],
      streams: 549134957,
      duration: 358,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
    {
      id: "003-05",
      album: "003",
      title: "Beat It",
      artists: ["Michael Jackson"],
      streams: 478532108,
      duration: 258,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
    {
      id: "003-06",
      album: "003",
      title: "Billie Jean",
      artists: ["Michael Jackson"],
      streams: 834271539,
      duration: 294,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
    {
      id: "003-07",
      album: "003",
      title: "Human Nature",
      artists: ["Michael Jackson"],
      streams: 123689142,
      duration: 248,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
    {
      id: "003-08",
      album: "003",
      title: "P.Y.T. (Pretty Young Thing)",
      artists: ["Michael Jackson"],
      streams: 102134789,
      duration: 239,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: false,
    },
    {
      id: "003-09",
      album: "003",
      title: "The Lady in My Life",
      artists: ["Michael Jackson"],
      streams: 74352103,
      duration: 299,
      image: "/playerControls/Michael_Jackson_-_Thriller.png",
      isLiked: true,
    },
  ],
};

const theMiseducationOfLaurynHill: TAlbum = {
  id: "004",
  name: "The Miseducation of Lauryn Hill",
  artist: "Ms. Lauryn Hill",
  year: 1998,
  duration: 4765, // 1 hora, 19 minutos y 25 segundos
  image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
  colorFrom: "#7f2f2f",
  colorTo: "#621318",
  isLiked: true,
  songList: [
    {
      id: "004-01",
      album: "004",
      title: "Intro",
      artists: ["Ms. Lauryn Hill"],
      streams: 4531981,
      duration: 66,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
    {
      id: "004-02",
      album: "004",
      title: "Lost Ones",
      artists: ["Ms. Lauryn Hill"],
      streams: 189317426,
      duration: 309,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-03",
      album: "004",
      title: "Ex-Factor",
      artists: ["Ms. Lauryn Hill"],
      streams: 274832951,
      duration: 337,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-04",
      album: "004",
      title: "To Zion",
      artists: ["Ms. Lauryn Hill", "Carlos Santana"],
      streams: 132439788,
      duration: 366,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-05",
      album: "004",
      title: "Doo Wop (That Thing)",
      artists: ["Ms. Lauryn Hill"],
      streams: 415698274,
      duration: 305,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-06",
      album: "004",
      title: "Superstar",
      artists: ["Ms. Lauryn Hill"],
      streams: 98423576,
      duration: 256,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
    {
      id: "004-07",
      album: "004",
      title: "Final Hour",
      artists: ["Ms. Lauryn Hill"],
      streams: 67898413,
      duration: 269,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
    {
      id: "004-08",
      album: "004",
      title: "When It Hurts So Bad",
      artists: ["Ms. Lauryn Hill"],
      streams: 104523872,
      duration: 293,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-09",
      album: "004",
      title: "I Used to Love Him",
      artists: ["Ms. Lauryn Hill", "Mary J. Blige"],
      streams: 89347821,
      duration: 323,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-10",
      album: "004",
      title: "Forgive Them Father",
      artists: ["Ms. Lauryn Hill"],
      streams: 67486359,
      duration: 328,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
    {
      id: "004-11",
      album: "004",
      title: "Every Ghetto, Every City",
      artists: ["Ms. Lauryn Hill"],
      streams: 58937823,
      duration: 296,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
    {
      id: "004-12",
      album: "004",
      title: "Nothing Even Matters",
      artists: ["Ms. Lauryn Hill", "D'Angelo"],
      streams: 132948576,
      duration: 361,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-13",
      album: "004",
      title: "Everything Is Everything",
      artists: ["Ms. Lauryn Hill"],
      streams: 198712643,
      duration: 237,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-14",
      album: "004",
      title: "The Miseducation of Lauryn Hill",
      artists: ["Ms. Lauryn Hill"],
      streams: 125612978,
      duration: 265,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-15",
      album: "004",
      title: "Can't Take My Eyes Off of You",
      artists: ["Ms. Lauryn Hill"],
      streams: 305947136,
      duration: 226,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: true,
    },
    {
      id: "004-16",
      album: "004",
      title: "Tell Him",
      artists: ["Ms. Lauryn Hill"],
      streams: 87219345,
      duration: 259,
      image: "/playerControls/The_Miseducation_of_Lauryn_Hill.png",
      isLiked: false,
    },
  ],
};

const nevermind: TAlbum = {
  id: "005",
  name: "Nevermind",
  artist: "Nirvana",
  year: 1991,
  duration: 2940, // 49 minutos
  image: "/playerControls/NirvanaNevermindalbumcover.jpg",
  colorFrom: "#0060a8",
  colorTo: "#003074",
  isLiked: true,
  songList: [
    {
      id: "005-01",
      album: "005",
      title: "Smells Like Teen Spirit",
      artists: ["Nirvana"],
      streams: 1356729814,
      duration: 301,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
    {
      id: "005-02",
      album: "005",
      title: "In Bloom",
      artists: ["Nirvana"],
      streams: 432189342,
      duration: 254,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
    {
      id: "005-03",
      album: "005",
      title: "Come as You Are",
      artists: ["Nirvana"],
      streams: 891245376,
      duration: 219,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
    {
      id: "005-04",
      album: "005",
      title: "Breed",
      artists: ["Nirvana"],
      streams: 289358712,
      duration: 183,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-05",
      album: "005",
      title: "Lithium",
      artists: ["Nirvana"],
      streams: 576129874,
      duration: 257,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
    {
      id: "005-06",
      album: "005",
      title: "Polly",
      artists: ["Nirvana"],
      streams: 234579143,
      duration: 179,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-07",
      album: "005",
      title: "Territorial Pissings",
      artists: ["Nirvana"],
      streams: 156781364,
      duration: 142,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-08",
      album: "005",
      title: "Drain You",
      artists: ["Nirvana"],
      streams: 298769842,
      duration: 223,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
    {
      id: "005-09",
      album: "005",
      title: "Lounge Act",
      artists: ["Nirvana"],
      streams: 145681923,
      duration: 156,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-10",
      album: "005",
      title: "Stay Away",
      artists: ["Nirvana"],
      streams: 134569021,
      duration: 212,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-11",
      album: "005",
      title: "On a Plain",
      artists: ["Nirvana"],
      streams: 198769134,
      duration: 196,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: false,
    },
    {
      id: "005-12",
      album: "005",
      title: "Something in the Way",
      artists: ["Nirvana"],
      streams: 654328192,
      duration: 231,
      image: "/playerControls/NirvanaNevermindalbumcover.jpg",
      isLiked: true,
    },
  ],
};

const toPimpAButterfly: TAlbum = {
  id: "006",
  name: "To Pimp a Butterfly",
  artist: "Kendrick Lamar",
  year: 2015,
  duration: 4787, // 1 hora, 19 minutos y 47 segundos
  image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
  colorFrom: "#535353",
  colorTo: "#363636",
  isLiked: true,
  songList: [
    {
      id: "006-01",
      album: "006",
      title: "Wesley's Theory",
      artists: ["Kendrick Lamar", "George Clinton", "Thundercat"],
      streams: 124569832,
      duration: 292,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-02",
      album: "006",
      title: "For Free? (Interlude)",
      artists: ["Kendrick Lamar"],
      streams: 78543742,
      duration: 122,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-03",
      album: "006",
      title: "King Kunta",
      artists: ["Kendrick Lamar"],
      streams: 345689314,
      duration: 220,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-04",
      album: "006",
      title: "Institutionalized",
      artists: ["Kendrick Lamar", "Bilal", "Anna Wise", "Snoop Dogg"],
      streams: 93457826,
      duration: 284,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-05",
      album: "006",
      title: "These Walls",
      artists: ["Kendrick Lamar", "Bilal", "Anna Wise", "Thundercat"],
      streams: 112348271,
      duration: 320,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-06",
      album: "006",
      title: "u",
      artists: ["Kendrick Lamar"],
      streams: 95432781,
      duration: 273,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-07",
      album: "006",
      title: "Alright",
      artists: ["Kendrick Lamar"],
      streams: 456792813,
      duration: 219,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-08",
      album: "006",
      title: "For Sale? (Interlude)",
      artists: ["Kendrick Lamar"],
      streams: 62346125,
      duration: 282,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-09",
      album: "006",
      title: "Momma",
      artists: ["Kendrick Lamar"],
      streams: 83457623,
      duration: 277,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-10",
      album: "006",
      title: "Hood Politics",
      artists: ["Kendrick Lamar"],
      streams: 78901567,
      duration: 294,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-11",
      album: "006",
      title: "How Much a Dollar Cost",
      artists: ["Kendrick Lamar", "James Fauntleroy", "Ronald Isley"],
      streams: 123459162,
      duration: 270,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-12",
      album: "006",
      title: "Complexion (A Zulu Love)",
      artists: ["Kendrick Lamar", "Rapsody"],
      streams: 92346924,
      duration: 260,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-13",
      album: "006",
      title: "The Blacker the Berry",
      artists: ["Kendrick Lamar"],
      streams: 198768431,
      duration: 308,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-14",
      album: "006",
      title: "You Ain’t Gotta Lie (Momma Said)",
      artists: ["Kendrick Lamar"],
      streams: 71234829,
      duration: 245,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: false,
    },
    {
      id: "006-15",
      album: "006",
      title: "i",
      artists: ["Kendrick Lamar"],
      streams: 267893416,
      duration: 315,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
    {
      id: "006-16",
      album: "006",
      title: "Mortal Man",
      artists: ["Kendrick Lamar"],
      streams: 85432564,
      duration: 732,
      image: "/playerControls/ab67616d00001e02cdb645498cd3d8a2db4d05e1.jpeg",
      isLiked: true,
    },
  ],
};

const goodKidMaadCity: TAlbum = {
  id: "007",
  name: "Good Kid, M.A.A.D City",
  artist: "Kendrick Lamar",
  year: 2012,
  duration: 4315, // 1 hora, 11 minutos y 55 segundos
  image: "/playerControls/KendrickGKMC.jpg",
  colorFrom: "#546E7A",
  colorTo: "#263238",
  isLiked: true,
  songList: [
    {
      id: "007-01",
      album: "007",
      title: "Sherane a.k.a Master Splinter’s Daughter",
      artists: ["Kendrick Lamar"],
      streams: 114572983,
      duration: 247,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: false,
    },
    {
      id: "007-02",
      album: "007",
      title: "Bitch, Don’t Kill My Vibe",
      artists: ["Kendrick Lamar"],
      streams: 398251672,
      duration: 312,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-03",
      album: "007",
      title: "Backseat Freestyle",
      artists: ["Kendrick Lamar"],
      streams: 215673984,
      duration: 231,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-04",
      album: "007",
      title: "The Art of Peer Pressure",
      artists: ["Kendrick Lamar"],
      streams: 165438921,
      duration: 309,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: false,
    },
    {
      id: "007-05",
      album: "007",
      title: "Money Trees",
      artists: ["Kendrick Lamar", "Jay Rock"],
      streams: 489236519,
      duration: 386,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-06",
      album: "007",
      title: "Poetic Justice",
      artists: ["Kendrick Lamar", "Drake"],
      streams: 382759186,
      duration: 305,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-07",
      album: "007",
      title: "good kid",
      artists: ["Kendrick Lamar"],
      streams: 139824761,
      duration: 224,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: false,
    },
    {
      id: "007-08",
      album: "007",
      title: "m.A.A.d city",
      artists: ["Kendrick Lamar", "MC Eiht"],
      streams: 315749826,
      duration: 341,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-09",
      album: "007",
      title: "Swimming Pools (Drank)",
      artists: ["Kendrick Lamar"],
      streams: 496382159,
      duration: 276,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-10",
      album: "007",
      title: "Sing About Me, I’m Dying of Thirst",
      artists: ["Kendrick Lamar"],
      streams: 187526341,
      duration: 743,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
    {
      id: "007-11",
      album: "007",
      title: "Real",
      artists: ["Kendrick Lamar", "Anna Wise"],
      streams: 92567341,
      duration: 307,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: false,
    },
    {
      id: "007-12",
      album: "007",
      title: "Compton",
      artists: ["Kendrick Lamar", "Dr. Dre"],
      streams: 132845761,
      duration: 250,
      image: "/playerControls/KendrickGKMC.jpg",
      isLiked: true,
    },
  ],
};

const darkSideOfTheMoon: TAlbum = {
  id: "008",
  name: "The Dark Side of the Moon",
  artist: "Pink Floyd",
  year: 1973,
  duration: 2580, // 43 minutos
  image: "/playerControls/Dark_Side_of_the_Moon.png",
  colorFrom: "#2e2e2e",
  colorTo: "#0a0a0a",
  isLiked: true,
  songList: [
    {
      id: "008-01",
      album: "008",
      title: "Speak to Me",
      artists: ["Pink Floyd"],
      streams: 82345678,
      duration: 90,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: false,
    },
    {
      id: "008-02",
      album: "008",
      title: "Breathe (In the Air)",
      artists: ["Pink Floyd"],
      streams: 192384756,
      duration: 163,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
    {
      id: "008-03",
      album: "008",
      title: "On the Run",
      artists: ["Pink Floyd"],
      streams: 128394756,
      duration: 216,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: false,
    },
    {
      id: "008-04",
      album: "008",
      title: "Time",
      artists: ["Pink Floyd"],
      streams: 284756392,
      duration: 413,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
    {
      id: "008-05",
      album: "008",
      title: "The Great Gig in the Sky",
      artists: ["Pink Floyd"],
      streams: 243567198,
      duration: 276,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
    {
      id: "008-06",
      album: "008",
      title: "Money",
      artists: ["Pink Floyd"],
      streams: 372849165,
      duration: 382,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
    {
      id: "008-07",
      album: "008",
      title: "Us and Them",
      artists: ["Pink Floyd"],
      streams: 198375641,
      duration: 462,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: false,
    },
    {
      id: "008-08",
      album: "008",
      title: "Any Colour You Like",
      artists: ["Pink Floyd"],
      streams: 103284756,
      duration: 205,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: false,
    },
    {
      id: "008-09",
      album: "008",
      title: "Brain Damage",
      artists: ["Pink Floyd"],
      streams: 172384951,
      duration: 228,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
    {
      id: "008-10",
      album: "008",
      title: "Eclipse",
      artists: ["Pink Floyd"],
      streams: 162847395,
      duration: 123,
      image: "/playerControls/Dark_Side_of_the_Moon.png",
      isLiked: true,
    },
  ],
};

const starboy: TAlbum = {
  id: "010",
  name: "Starboy",
  artist: "The Weeknd",
  year: 2016,
  duration: 4180, // 1 hora, 9 minutos y 40 segundos
  image: "/playerControls/The_Weeknd_-_Starboy.png",
  colorFrom: "#a00030",
  colorTo: "#650014",
  isLiked: true,
  songList: [
    {
      id: "010-01",
      album: "010",
      title: "Starboy",
      artists: ["The Weeknd", "Daft Punk"],
      streams: 2109348571,
      duration: 230,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-02",
      album: "010",
      title: "Party Monster",
      artists: ["The Weeknd"],
      streams: 720198374,
      duration: 255,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-03",
      album: "010",
      title: "False Alarm",
      artists: ["The Weeknd"],
      streams: 510349812,
      duration: 231,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-04",
      album: "010",
      title: "Reminder",
      artists: ["The Weeknd"],
      streams: 934875203,
      duration: 223,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-05",
      album: "010",
      title: "Rockin’",
      artists: ["The Weeknd"],
      streams: 389472018,
      duration: 223,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-06",
      album: "010",
      title: "Secrets",
      artists: ["The Weeknd"],
      streams: 472910385,
      duration: 267,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-07",
      album: "010",
      title: "True Colors",
      artists: ["The Weeknd"],
      streams: 298347201,
      duration: 220,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-08",
      album: "010",
      title: "Stargirl Interlude",
      artists: ["The Weeknd", "Lana Del Rey"],
      streams: 389201834,
      duration: 101,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-09",
      album: "010",
      title: "Sidewalks",
      artists: ["The Weeknd", "Kendrick Lamar"],
      streams: 534920183,
      duration: 214,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-10",
      album: "010",
      title: "Six Feet Under",
      artists: ["The Weeknd", "Future"],
      streams: 392014782,
      duration: 206,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-11",
      album: "010",
      title: "Love to Lay",
      artists: ["The Weeknd"],
      streams: 274839201,
      duration: 195,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-12",
      album: "010",
      title: "A Lonely Night",
      artists: ["The Weeknd"],
      streams: 398472018,
      duration: 217,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-13",
      album: "010",
      title: "Attention",
      artists: ["The Weeknd"],
      streams: 238901847,
      duration: 223,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-14",
      album: "010",
      title: "Ordinary Life",
      artists: ["The Weeknd"],
      streams: 348920183,
      duration: 244,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-15",
      album: "010",
      title: "Nothing Without You",
      artists: ["The Weeknd"],
      streams: 210938475,
      duration: 213,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-16",
      album: "010",
      title: "All I Know",
      artists: ["The Weeknd", "Future"],
      streams: 284719384,
      duration: 287,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: false,
    },
    {
      id: "010-17",
      album: "010",
      title: "Die for You",
      artists: ["The Weeknd"],
      streams: 1293847560,
      duration: 269,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
    {
      id: "010-18",
      album: "010",
      title: "I Feel It Coming",
      artists: ["The Weeknd", "Daft Punk"],
      streams: 1539847581,
      duration: 269,
      image: "/playerControls/The_Weeknd_-_Starboy.png",
      isLiked: true,
    },
  ],
};

const likedAlbums = [
  demonDays,
  thriller,
  theMiseducationOfLaurynHill,
  inRainbows,
  toPimpAButterfly,
  nevermind,
  goodKidMaadCity,
  darkSideOfTheMoon,
  starboy,
];

export {
  likedAlbums,
  demonDays,
  thriller,
  theMiseducationOfLaurynHill,
  inRainbows,
  toPimpAButterfly,
  nevermind,
};
